server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**
            - After=2020-03-11T11:08:02.532+08:00[Asia/Shanghai]
        - id: payment_routh2
          uri: lb:////CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#      routes:
#        - id: payment_routh             #路由的ID,没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供路由的服务地址
#          predicates:
#            - Path=/payment/get/**      #断言，路径相匹配的进行路由
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka
  instance:
    prefer-ip-address: true  #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 2 #收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除